name: Sync from Upstream (TonyJiangWJ/mimotion)

on:
  # ✅ 每天北京时间凌晨 3 点同步一次
  schedule:
    - cron: '0 8 * * *'

  # ✅ 手动触发
  workflow_dispatch:
    inputs:
      reason:
        description: 'Manual trigger reason'
        required: false
        default: 'Manual sync'

  # ✅ 上游仓库有变动时自动触发（通过 repository_dispatch）
  repository_dispatch:
    types: [sync_trigger]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/TonyJiangWJ/mimotion.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          # 确保本地 encrypted_tokens.data 不被上游覆盖
          git checkout --ours encrypted_tokens.data || true
          git add encrypted_tokens.data || true

          # 合并上游 main 分支
          git merge upstream/main --no-edit || true

          # 再次确保文件未被覆盖
          git checkout --ours encrypted_tokens.data || true
          git add encrypted_tokens.data || true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main || echo "Nothing to push"
